const data={sets:[
{t:'07:42',day:'2026-05-08',sport:'strength',ex:'DB Shoulder Press',set:1,w:50,reps:8,rpe:8,rest:'2:00',note:'clean'},
{t:'07:46',day:'2026-05-08',sport:'strength',ex:'DB Shoulder Press',set:2,w:50,reps:8,rpe:8.5,rest:'2:15',note:'slower lockout'},
{t:'07:51',day:'2026-05-08',sport:'strength',ex:'DB Shoulder Press',set:3,w:50,reps:7,rpe:9,rest:'2:30',note:'hold 50 until 8/8/8'},
{t:'08:02',day:'2026-05-08',sport:'strength',ex:'Cable Lateral Raise',set:1,w:25,reps:12,rpe:8,rest:'1:15',note:'strict'},
{t:'08:05',day:'2026-05-08',sport:'strength',ex:'Cable Lateral Raise',set:2,w:25,reps:12,rpe:8,rest:'1:15',note:'strict'},
{t:'08:11',day:'2026-05-08',sport:'strength',ex:'Rear Delt Fly',set:1,w:100,reps:12,rpe:8,rest:'1:30',note:'progress'},
{t:'08:15',day:'2026-05-08',sport:'strength',ex:'Rear Delt Fly',set:2,w:100,reps:12,rpe:8.5,rest:'1:30',note:'good'},
{t:'08:19',day:'2026-05-08',sport:'strength',ex:'Rear Delt Fly',set:3,w:100,reps:10,rpe:9,rest:'—',note:'next 12/12/10+'},
{t:'18:10',day:'2026-05-02',sport:'bike',ex:'Bike endurance',set:1,w:151,reps:143,rpe:6,rest:'—',note:'73.1km avg power'},
{t:'20:40',day:'2026-05-02',sport:'run',ex:'Brick run',set:1,w:0,reps:30,rpe:7,rest:'—',note:'5.47km @ 5:31/km'}],
history:{'DB Shoulder Press':[{d:'04-21',load:45,reps:10,est:60},{d:'04-28',load:45,reps:10,est:60},{d:'05-08',load:50,reps:8,est:63.3}], 'Rear Delt Fly':[{d:'04-22',load:90,reps:12,est:126},{d:'05-01',load:100,reps:10,est:133},{d:'05-08',load:100,reps:12,est:140}], 'Cable Lateral Raise':[{d:'04-22',load:20,reps:15,est:30},{d:'05-01',load:25,reps:10,est:33},{d:'05-08',load:25,reps:12,est:35}], 'Lat Pulldown':[{d:'04-24',load:150,reps:10,est:200},{d:'05-01',load:160,reps:8,est:203},{d:'05-07',load:160,reps:9,est:208}], 'Leg Curl':[{d:'04-23',load:110,reps:10,est:147},{d:'05-05',load:120,reps:10,est:160}]},
forecast:[{ex:'DB Shoulder Press',why:'Last set failed at 7 reps but first two sets stable.',next:'50 lb × 8 / 8 / 8',len:'12–14 min',rule:'If set 3 <8 again: keep 50, add 30s rest.'},{ex:'Rear Delt Fly',why:'100×12/12/10 shows strong adaptation.',next:'100 lb × 12 / 12 / 11+',len:'7–9 min',rule:'Do not jump to 110 until 12/12/12.'},{ex:'Cable Lateral Raise',why:'Side delts need quality volume without elbow fatigue.',next:'25 lb × 13 / 12 / 12',len:'6–8 min',rule:'Tempo 2 sec down, no body English.'},{ex:'Bike aerobic',why:'Triathlon engine still under-specified; protect strength gains.',next:'Z2 75–90 min @ 145–155W',len:'75–90 min',rule:'Fuel 40–60g carbs/hour.'},{ex:'Run off bike',why:'Brick pace known; avoid overloading legs after heavy lower body.',next:'20–30 min easy brick @ 5:45–6:05/km',len:'20–30 min',rule:'Only progress if calves/hamstrings green.'}],
missing:['Intervals API key','bodyweight daily','protein/kcal daily','sleep + HRV','RPE/RIR per set','race date + course']};
const $=id=>document.getElementById(id);let view='today';function sets(){let d=$('day').value,s=$('sport').value;return data.sets.filter(x=>(!d||x.day===d||view!=='today')&&(s==='all'||x.sport===s))}function est1rm(w,r){return w&&r?w*(1+r/30):0}function renderStrip(){const ss=sets(),strength=ss.filter(x=>x.sport==='strength'),ton=strength.reduce((a,x)=>a+x.w*x.reps,0),avgRpe=ss.reduce((a,x)=>a+x.rpe,0)/(ss.length||1);$('coachStrip').innerHTML=[['Logged rows',ss.length,'rep/interval records','good'],['Today tonnage',Math.round(ton).toLocaleString()+' lb','strength only','good'],['Avg intensity',avgRpe.toFixed(1),'RPE proxy',avgRpe>8.6?'warn':'good'],['Forecast ready','5 actions','next exercise/weight/time','good'],['Data quality','42%','API + recovery missing','warn'],['Coach verdict','Proceed','controlled progression','good']].map(x=>`<div class="tile ${x[3]}"><small>${x[0]}</small><b>${x[1]}</b><small>${x[2]}</small></div>`).join('')}
function renderFeed(){const rows=sets();$('feedTable').innerHTML=`<div class="row header"><span>time</span><span>exercise</span><span>set</span><span>lb</span><span>reps</span><span>RPE</span><span>coach note</span><span>e1RM</span></div>`+rows.map(x=>`<div class="row"><span>${x.t}</span><strong>${x.ex}</strong><span class="tag">${x.set}</span><span>${x.w||'—'}</span><span>${x.reps}</span><span class="tag ${x.rpe>=9?'amber':'green'}">${x.rpe}</span><span>${x.note}</span><b>${x.w?est1rm(x.w,x.reps).toFixed(1):'—'}</b></div>`).join('')}
function renderForecast(){$('forecastList').innerHTML=data.forecast.map((f,i)=>`<div class="forecast"><div class="rank">${i+1}</div><div><b>${f.ex}</b><small>${f.why}</small><br><em>${f.next}</em><br><small>${f.rule}</small></div><strong>${f.len}</strong></div>`).join('')}
function drawExercise(){const ex=$('exerciseSelect').value,arr=data.history[ex]||[],c=$('exerciseChart'),ctx=c.getContext('2d'),r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=r.width*dpr;c.height=230*dpr;ctx.scale(dpr,dpr);let w=r.width,h=230,p=28;ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.08)';for(let i=0;i<4;i++){let y=p+i*(h-p*2)/3;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}let max=Math.max(...arr.map(x=>x.est),1);ctx.strokeStyle='#73f5a8';ctx.lineWidth=2;ctx.beginPath();arr.forEach((x,i)=>{let xx=p+i*(w-p*2)/(arr.length-1||1),yy=h-p-(x.est/max)*(h-p*2);i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.stroke();arr.forEach((x,i)=>{let xx=p+i*(w-p*2)/(arr.length-1||1),yy=h-p-(x.est/max)*(h-p*2);ctx.fillStyle='#73f5a8';ctx.beginPath();ctx.arc(xx,yy,4,0,7);ctx.fill();ctx.fillStyle='#8c9d92';ctx.fillText(x.d,xx-12,h-8);ctx.fillStyle='#edf5ef';ctx.fillText(Math.round(x.est),xx-8,yy-9)})}
function renderEvolution(){let exs=Object.keys(data.history);$('exerciseSelect').innerHTML=exs.map(x=>`<option>${x}</option>`).join('');$('exerciseSelect').onchange=()=>{drawExercise();renderMovementNotes()};renderMovementNotes();setTimeout(drawExercise,0)}function renderMovementNotes(){let ex=$('exerciseSelect').value,arr=data.history[ex],last=arr[arr.length-1],prev=arr[arr.length-2]||last,gain=((last.est-prev.est)/prev.est*100)||0;$('movementNotes').innerHTML=[['Current e1RM',last.est.toFixed(1),'estimated from latest best set'],['Last delta',gain.toFixed(1)+'%','exercise-specific progression'],['Next decision',gain>3?'hold + consolidate':'micro-progress','AI coach rule'],['Risk flag',last.reps<8?'strength limit':'volume OK','based on latest reps']].map(c=>`<div class="card"><b>${c[1]}</b><small>${c[0]} · ${c[2]}</small><div class="bar"><span style="width:${Math.min(100,Math.abs(gain)*15+35)}%"></span></div></div>`).join('')}
function renderBottom(){$('enduranceCards').innerHTML=[['Bike','Next: Z2 75–90 min @ 145–155W','Do not chase FTP before Intervals import.'],['Run','Next: easy brick 20–30 min','Protect legs while gym tonnage is high.'],['Swim','Need sessions','Minimum 2/wk technique + aerobic.'],['Fuel','40–60g carbs/hour on long bike','Bulk supports endurance if timed.']].map(c=>`<div class="card"><b>${c[0]}</b><small>${c[1]}<br>${c[2]}</small></div>`).join('');$('readiness').innerHTML=['Shoulders: green, progress but keep form','Leg fatigue: unknown without soreness score','Endurance load: safe until Intervals sync','Today decision: log every set live'].map(x=>`<div class="card"><b>${x}</b></div>`).join('');$('nutrition').innerHTML=['Protein target: 160g+','Carbs around bike/run: mandatory','Weight trend needed: morning scale','Goal: bulk slowly, not sloppy'].map(x=>`<div class="card"><b>${x}</b></div>`).join('');$('missing').innerHTML=data.missing.map(x=>`<div class="card"><b>${x}</b><small>needed for smarter forecasts</small></div>`).join('')}
function bind(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'));b.classList.add('active');view=b.dataset.view;render()});['day','sport','density'].forEach(id=>$(id).oninput=render);$('addSetBtn').onclick=()=>$('composer').classList.toggle('hidden');$('saveSet').onclick=()=>{let ex=$('exerciseInput').value||'New exercise',w=+$('weightInput').value||0,reps=+$('repsInput').value||0,rpe=+$('rpeInput').value.replace('RPE ','')||8;data.sets.unshift({t:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),day:$('day').value,sport:'strength',ex,set:1,w,reps,rpe,rest:'—',note:'live input'});render()}}
function render(){document.body.classList.toggle('compact',$('density').value==='0');renderStrip();renderFeed();renderForecast();renderEvolution();renderBottom()}bind();render();addEventListener('resize',drawExercise);